#!/bin/sh

if [ "$1" == "clean" ]
then
	echo 'cleaning ...'
	rm -f parser_generator.tab.c lex.yy.c run_parser.out lexical_analyzer.out #parser_generator.tab.h 
	exit 0
fi

flex lexical_analyzer.l
bison -d parser_generator.y
gcc parser_generator.tab.c lex.yy.c -o run_parser.out

astFile="$(cut -d'.' -f1 <<<"$1")"
ext=".ast"
astFile=$astFile$ext

./run_parser.out $1 > $astFile
