#!/bin/sh

if [ "$1" == "clean" ]
then
	echo 'cleaning ...'
	rm -f parser_generator.tab.h parser_generator.tab.c lex.yy.c run_parser.out
	exit 0
fi

flex lexical_analyser.l
bison -d parser_generator.y
gcc parser_generator.tab.c lex.yy.c -o run_parser.out
./run_parser.out $1
