#!/bin/sh

#header_file="parser_generator.tab.h"
#if [ ! -f "$header_file" ]
#then
#	echo "" > "$header_file"
#fi

#flex lexical_analyzer.l
#gcc lex.yy.c -o lexical_analyzer.out

#./lexical_analyzer.out $1

flex -o typeid.yy.c lexanalyze.l
gcc typeid.yy.c -o find_typeid.out

./find_typeid.out $1
